### PR TITLE
Fix null pointer exception when transaction is not found

### LINKED ISSUE #33: Error 500 (null pointer) when transaction not found
Example: https://api.keyconnect.app/v1/blockchains/xrp/transactions/F6BDDA801229ADCCDEF3D0771C84ED86730DBE28B5537A226BE145FE49E09F7F?network=mainnet

```
{
    "timestamp": 1612641651924,
    "status": 500,
    "error": "Internal Server Error",
    "message": "org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke \"String.toCharArray()\" because \"val\" is null",
    "path": "/v1/blockchains/xrp/transactions/F6BDDA801229ADCCDEF3D0771C84ED86730DBE28B5537A226BE145FE49E09F7F"
}
```

### PR DESCRIPTION
**Pull request by manthanhd**
Closes #33

### CODE REVIEW

**Comment by manthanhd** [comment]
@elmurci - with the fix the output is the following

```
 curl http://localhost:8080/v1/blockchains/xrp/transactions/F6BDDA801229ADCCDEF3D0771C84ED86730DBE28B5537A226BE145FE49E09F7F?network=mainnet
{"chainId":"xrp","network":"mainnet","server":"s1.ripple.com","transaction":{"status":"unknown","destinationTag":"null","fee":{"currency":"drops"},"amount":{"amount":"0","currency":"xrp"}}}
```

Is this what you expect or do you expect a 404?

**Comment by elmurci** [comment]
> @elmurci - with the fix the output is the following
> 
> ```
>  curl http://localhost:8080/v1/blockchains/xrp/transactions/F6BDDA801229ADCCDEF3D0771C84ED86730DBE28B5537A226BE145FE49E09F7F?network=mainnet
> {"chainId":"xrp","network":"mainnet","server":"s1.ripple.com","transaction":{"status":"unknown","destinationTag":"null","fee":{"currency":"drops"},"amount":{"amount":"0","currency":"xrp"}}}
> ```
> 
> Is this what you expect or do you expect a 404?

hmm yes, I would expect a 404.

**Comment by manthanhd** [comment]
@elmurci - fixed it
```
curl http://localhost:8080/v1/blockchains/xrp/transactions/F6BDDA801229ADCCDEF3D0771C84ED86730DBE28B5537A226BE145FE49E09F7F?network=mainnet
{"timestamp":1612860143242,"status":404,"error":"Not Found","message":"Requested transaction F6BDDA801229ADCCDEF3D0771C84ED86730DBE28B5537A226BE145FE49E09F7F was not found on xrp mainnet","path":"/v1/blockchains/xrp/transactions/F6BDDA801229ADCCDEF3D0771C84ED86730DBE28B5537A226BE145FE49E09F7F"}
```

Response code is 404 too.

**Comment by manthanhd** [comment]
Also handling errors in getting transactions for an account and account info endpoints too

**Pull request merged**
